use_frameworks!

platform :ios, '10.0'

target 'WSTabViewControlSwift_Example' do
  pod 'WSTabViewControlSwift', :path => '../'

  target 'WSTabViewControlSwift_Tests' do
    inherit! :search_paths

    
  end
end
